apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment-canary
  labels:
    role: app
    version: "2.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      role: app
  template:
    metadata:
      labels:
        role: app
        version: "2.0"
    spec:
      
      containers:
      - name: app
        image: image_id
        resources:
          requests:
            cpu: 10m
        
            
     
   
